### ISSUE TITLE
Unbound constant

### ISSUE THREAD

**Issue by bmcfluff** [ucsd-progsys/liquid-fixpoint#111]
See:

https://github.com/ucsd-progsys/liquid-fixpoint/blob/master/external/fixpoint/tests/liquidhaskell_tests/pos/vecloop.hs.fq#L86

"rng" appears in a couple qualifiers but is otherwise unbound, leading (Haskell) Fixpoint to complain of an unknown constant. Is this a problem with fixpoint, or with liquidhaskell for generating such an fq file?

**Comment by ranjitjhala** [comment]
fixed this by fixing the sort-checking during instantiation, but it reveals a NEW bug, which is lack of support for `num`  -- see `tests/pos/num00.fq` in the new `num` branch.

**Comment by ranjitjhala** [comment]
should be fixed by: https://github.com/ucsd-progsys/liquid-fixpoint/pull/115

@bmcfluff can you confirm?

**Comment by ranjitjhala** [comment]
while `rng` is fishy -- and almost surely a sign of some badness in LH (@nikivazou can you explain it?) -- it is *not* a malformed input. In short, this is a problem with *fixpoint* because only well-sorted qualifiers should be instantiated and so I am puzzled as to how this fellow gets instantiated. [at any rate, fixed]
