### ISSUE TITLE
Better not name your sort "int*"

### ISSUE THREAD

**Issue by BenjaminCosman** [ucsd-progsys/liquid-fixpoint#147]
See:

https://github.com/ucsd-progsys/liquid-fixpoint/blob/458e03d7fa2bef3831e11c308dee6ade696edcd4/tests/todo/int-name.fq

If you run with fixpoint --native -v, you'll see that the sort "intfoo" is getting parsed as "(int @(0))" instead of "@(0)". Probably easiest to ignore this bug and just avoid naming things int*, but I'm recording it anyway.

**Comment by christetreault** [comment]
I've just spent a little bit of time looking at this, so please forgive me if I've missed some subtlty, but it seems to me that this is probably just missing a `sepBy` or somesuch somewhere.

[here](https://github.com/ucsd-progsys/liquid-fixpoint/blob/master/src/Language/Fixpoint/Parse.hs#L340-L349) we have `fTyConP` which parses some reserved words, including "int".

[here](https://github.com/ucsd-progsys/liquid-fixpoint/blob/master/src/Language/Fixpoint/Parse.hs#L322-L330) we have `sortP'` which uses `fTyConP` (line [329](https://github.com/ucsd-progsys/liquid-fixpoint/blob/master/src/Language/Fixpoint/Parse.hs#L329)). On line [330](https://github.com/ucsd-progsys/liquid-fixpoint/blob/master/src/Language/Fixpoint/Parse.hs#L330) we have a call to [`tvarP`](https://github.com/ucsd-progsys/liquid-fixpoint/blob/master/src/Language/Fixpoint/Parse.hs#L334-L337) which parses "@" or a symbol. The commented line [325](https://github.com/ucsd-progsys/liquid-fixpoint/blob/master/src/Language/Fixpoint/Parse.hs#L325) suggests to me that "@" should have a higher parsing priority. Maybe if we swap 329 and 330 the situation will be improved?

**Comment by gridaphobe** [comment]
I believe the real problem is this wonderful line

https://github.com/ucsd-progsys/liquid-fixpoint/blob/master/src/Language/Fixpoint/Parse.hs#L107

This says that no character can be part of a valid identifier, which completely screws up the `reserved` parser. `reserved` parses the given string and then looks ahead to make sure that the next character is not a valid identifier character. 

So `reserved "int"`, given `"intfoo"`, **ought** to parse `"int"`, then see that the next character is `'f'` (which in a sane parser **would** be a valid `identLetter`) and bail out. But our parser is not sane, it claims there is no such thing as a valid identifier, so `reserved "int"` happily parses against `"intfoo"`.

**Comment by ranjitjhala** [comment]
we _should_ fix this...

**Comment by atondwal** [comment]
We fixed this at some point an forgot to close this issue (or just didn't realized that we fixed it, perhaps due to the alanz new parser stuff). Closing.

**Comment by ranjitjhala** [comment]
Whats the evidence that it was fixed btw? the above test works?


On Thu, Sep 14, 2017 at 10:40 AM, Anish Tondwalkar <notifications@github.com

**Comment by atondwal** [comment]
Yes, the above test now passes
