### ISSUE TITLE
Comparison of booleans

### ISSUE THREAD

**Issue by nikivazou** [ucsd-progsys/liquid-fixpoint#293]
Since fixpoint bool is SMT bool, we should not allow comparison of fixpoint bools. 
That is [line 786 of SortCheck](https://github.com/ucsd-progsys/liquid-fixpoint/blob/develop/src/Language/Fixpoint/SortCheck.hs#L786) that now is 

```
checkRelTy _ e _  t1 t2            = unless (t1 == t2)                 (throwError $ errRel e t1 t2)
```

should turn into 
```
checkRelTy _ e _  t1 t2            = unless (t1 == t2 && t1 /= boolSort)                 (throwError $ errRel e t1 t2)
```

But with this edit test https://github.com/ucsd-progsys/liquid-fixpoint/blob/develop/tests/pos/bool03.fq fails. 
Can I just remove this test?

**Comment by ranjitjhala** [comment]
Actually I am (pleasantly) surprised that

 https://github.com/ucsd-progsys/liquid-fixpoint/blob/develo
p/tests/pos/bool03.fq

works. Can you explain why we should _disable_ it?

Specifically, I don't follow the reasoning that:

"Since fixpoint bool is SMT bool, we should not allow comparison of
fixpoint bools."

can you say more? what exactly is the problem you are trying to solve?

**Comment by nikivazou** [comment]
Well, I added the non-boolean check because I got an SMT expression `x:bool, y:bool, x < y` which was not well sorted. 

But this .fq file turns out to be safe because the above expression is elaborated to `x:bool, y:bool, booltoInt x < boolToInt y`. 

So, maybe there was a problem in elaboration.
