### ISSUE TITLE
GHC 8.4.2 broken building

### ISSUE THREAD

**Issue by lucaciciriello** [ucsd-progsys/liquid-fixpoint#371]
With the new version of GHC (8.4.2) we got the following error:

src/Language/Fixpoint/Misc.hs:291:28: error:
    Ambiguous occurrence ‘<>’
    It could refer to either ‘Text.PrettyPrint.HughesPJ.<>’,
                             imported from ‘Text.PrettyPrint.HughesPJ’ at src/Language/Fixpoint/Misc.hs:34:1-64
                          or ‘Prelude.<>’,
                             imported from ‘Prelude’ at src/Language/Fixpoint/Misc.hs:41:1-40
                             (and originally defined in ‘GHC.Base’)
    |
291 | dcolon             = colon <> colon
    |                            ^^

And more...

**Comment by mhwombat** [comment]
I'm getting the same error with GHC 8.4.4.

**Comment by ranjitjhala** [comment]
Very odd thanks for pointing out, will take a look ASAP!

**Comment by mhwombat** [comment]
Sorry, I should have clarified that it's the version on Hackage (liquid-fixpoint-0.7.0.7) that causes this compilation error.

The latest version here on GitHub builds just fine with LTS Haskell 12.23 (ghc-8.4.4).

**Comment by mhwombat** [comment]
Is this version ready to release to Hackage?

FYI, I opened an [issue](https://github.com/NixOS/nixpkgs/issues/52418) on Nixpkgs about this.

**Comment by ranjitjhala** [comment]
Oh, in that case would it suffice to update the version on hackage [which is anyways due...]

**Comment by JakobBruenker** [comment]
Hi, @ranjitjhala any update on this? It looks like the version on hackage is still 0.7.0.7

**Comment by ranjitjhala** [comment]
Sorry, was on vacation and just got back will look into this ASAP!

**Comment by curiousleo** [comment]
This project definitely builds against GHC 8.10.7 as that is what's used in CI: https://github.com/ucsd-progsys/liquid-fixpoint/blob/3438be3ddf1823aab84b47b0ad34f03640ea384c/stack.yaml#L3

I guess this issue can be closed in the sense of "there is a newer version of GHC that you can use for which we know `liquid-fixpoint` builds"?

Alternatively, the CI build could run against several GHC versions to communicate (and test) the intent that `liquid-fixpoint` is compatible with them. As of right now, `liquid-fixpoint` only builds against 8.10.7 (via `stack.yaml`). Since `liquidhaskell` builds against 8.10.7 and 9.0.1, `liquid-fixpoint` is built on 9.0.1 too (but not on every build since `liquidhaskell` pins `liquid-fixpoint`).

Overall, I think that a clear statement regarding GHC compatibility would be useful. The README contains detailed instructions regarding versioning, but I couldn't find anything related to GHC compatibility.

**Comment by ranjitjhala** [comment]
Oops yes this is super old let’s close!
