### ISSUE TITLE
Understanding Horn solver

### ISSUE THREAD

**Issue by serras** [ucsd-progsys/liquid-fixpoint#448]
Hi, I don't know if this is the best way to ask for help with `liquid-fixpoint`, but here it goes. I'm working on a tool based on the "Local refinement typing" paper which has spit the following `.smt2` file:

```smt2
(fixpoint "--eliminate=horn")

(var $k1 ((Int)))
(var $k8 ((Int) (Int)))

(constraint
  (forall ((x Int) ($k1 x))
    (and
      (forall ((v26 Int) (and ($k1 v26) (x == v26))) ((v26 > 1)))
      (forall ((z Int) (z == x - 1))
        (forall ((r57 Int) (and (r57 == x - 1) (z == r57))) (($k8 x r57))))
    )
  )
)
```

I would expect it to give me back information that `$k1` should be somehow `\x -> x > 0`. However, to my surprise, the Horn Uniq and Horn Elimination phases leave me with an empty constraint:

```
Horn Uniq:
(forall ((x int) (k1 x))
 (and
  (forall ((v26 int) (and (k1 v26) (x == v26)))
   ((v26 > 1)))
  (forall ((z int) (z == x - 1))
   (forall ((r57 int) (and (r57 == x - 1) (z == r57)))
    ((k8 x r57))))))
Horn Elim:
(and)
```

Could you point me on the direction of understanding what is going on here?

**Comment by ranjitjhala** [comment]
Sure, this is a good place. The LH slack would be another option if you like, but this is great! 

Can you add the line

```
(qualif  Pos ((v Int)) (v > 0))
```

to the file and see what happens?

**Comment by serras** [comment]
It seems that if I change the first line to `eliminate=existentials`, it does what I want.

This raises two more questions:
- from what I understand, the original answer was right, in that making `$k1 x` to be constantly false is also a solution. As I understand, the "Local refinement typing" paper actually uses this fact.
- however, the other solver seems to work differently. Is that solver documented?

Thanks once again for your help :)

**Comment by ranjitjhala** [comment]
@serras  -- hmm, not sure why the `eliminate=existentials` does the right thing (@atondwal or @mkolosick do you know?)

(that feature is _very_ new and not super well documented ...) 

but can you say what it does - as in, what output are you looking for? 

(btw, are you using the API or the command line? If the former then I can easily replicate.)

With your constraint at the top, what is happening is

1. Since `$k1` is only on the LHS, it gets "solved" to false;
2. Since `$k2` is only on the RHS, it is not "used" and hence that constraint is trivially satisfied (e.g. to `true`)

which leaves fixpoint with no constraints to solve...

I _think_ the `existentials` thing perhaps disables the `false` solution -- @atondwal is that right?

**Comment by serras** [comment]
@ranjitjhala your description totally makes sense. I am slowly understanding how the solver works, and indeed solving things to false without any further condition makes complete sense!

**Comment by ranjitjhala** [comment]
Btw, after chatting with @atondwal I realized that indeed it's the "false"
thing that's going on.

But the "existentials" mode has to be more careful about setting things to
false, and hence, doesn't
in this example. (There is a new paper that describes it that is still
under submission...)
